export const LOAD_BOOKINGS_IN_PROGRESS = 'LOAD_BOOKINGS_IN_PROGRESS'
export const LOAD_BOOKINGS_SUCCESS = 'LOAD_BOOKINGS_SUCCESS'
export const LOAD_BOOKINGS_FAILURE = 'LOAD_BOOKINGS_FAILURE'

export const LOAD_PRODUCTS_IN_PROGRESS = 'LOAD_PRODUCTS_IN_PROGRESS'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE'

export const LOAD_SELLERS_IN_PROGRESS = 'LOAD_SELLERS_IN_PROGRESS'
export const LOAD_SELLERS_SUCCESS = 'LOAD_SELLERS_SUCCESS'
export const LOAD_SELLERS_FAILURE = 'LOAD_SELLERS_FAILURE'
